### ISSUE TITLE
Bungee: Bedwars Reloaded mit TPSigns

### ISSUE THREAD

**Issue by yannickko** [Yannici/bedwars-reloaded#296]
Hey kann mir mal bitte einer genau erklären wie man Bedwars mit Teleport Signs zum Laufen bekommt? Ich habe einen Server auf dem läuft die Lobby. Und von dem Server möchte ich auf einen Bedwars Server joinen. Dafür muss ich ja (noch) TeleportSigns nutzen. Aber wie? Habe noch nie Teleport Signs genutzt. Hab also da keine Ahnung was ich machen muss damit es mit Bedwars korrekt funktioniert.

Danke schon mal im vorraus.

**Comment by brainscript** [comment]
@yannickko Ich will dich nicht beleidigen, aber die Frage ist schon ziemlich dumm bzw. auf diesem Repo einfach nur unnötig. Ein Server ist ein Server, egal ob mit BedwarsRel oder ohne. Und die Config von Teleportsigns ist ja wirklich sehr kompliziert ... **NICHT**!
```
servers:
    bw1: # Der Name des Servers den du auf das Schild schreibst
        address: '127.0.0.1:25566' # Die Serveradresse
        displayname: 'BedWars 1' # Der Anzeigename
```
Den Rest wird in [etlichen Tutorials](http://de.lmgtfy.com/?q=teleportsigns+tutorial) gezeigt, die man mit hilfe einer "Google" genannten Suchmaschine finden kann, die das Internet nach deinem Suchwort durchsucht.
> Eine tolle Erfindung so eine [Suchmaschine](http://de.lmgtfy.com/?q=teleportsigns+tutorial) ...
