### ISSUE TITLE
SHEEP not spawn

### ISSUE THREAD

**Issue by MrFiliper** [Yannici/bedwars-reloaded#329]
If I buy TNT-Schaf, spawn onely TNT. Sheep not spawn. Please fix this.

**Comment by HobbyzockerLP** [comment]
Sheep can spawn, if you allowed to spawn animals on your world!

**Comment by Yannici** [comment]
And check if you have the correct shop.yml configuration!

**Comment by KUMbinder** [comment]
Same problem here. I think I need to have a look at the config as well...

**Comment by Yannici** [comment]
Often an issue by other plugins. Which spigot/bukkit version do you use?

**Comment by sebastianbinder** [comment]
Server is on Spigot 1.8.8.
Plugins: BedwarsRel, Multiverse-Core, BungeePerms, AntiAura (with dependencies: LibsDisguises, ProtocolLib)
Shop.yml:
```yml
            - item1:
                item: CLAY_BRICK
                amount: 64
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: MONSTER_EGG
                meta: 91
                amount: 1
```

**Comment by Yannici** [comment]
Should work, but I could imagine that LibsDisguises can be a problem, because this handles the mobs and does maybe manipulate the mob register.

**Comment by sebastianbinder** [comment]
Mm. Could be possible. But AntiAura (and I think almost any other anti-hack-plugin) uses libs like this one, since they need to check somehow if killaura is enabled… for now, I removed the sheep from the shop. I hope I'll find a solution….

**Comment by sebastianbinder** [comment]
@MrFiliper Please have a look at your different config files, if spawning of animals is allowed or not. For example your Multiverse world-config:
```yml
    spawning:
      ==: MVSpawnSettings
      animals:
        ==: MVSpawnSubSettings
        spawn: 'true'    # must be set true
        spawnrate: '-1'
        exceptions: []
```
@Yannici Any possibility to "test" sheep if there is only me in the game? It always tells me there is no player around, so I cannot test it…
