### ISSUE TITLE
TNT_sheep not spawned

### ISSUE THREAD

**Issue by Toshka17** [Yannici/bedwars-reloaded#353]
When using eggs, store bought nothing happens

**Comment by sebastianbinder** [comment]
Hi @Toshka17. It's pretty hard to give you support when there is almost no information at all. Please upload at least your shop.yml and tell us if there are any errors on the console.

**Comment by Toshka17** [comment]
I have bungee, not multiverse,

http://pastebin.com/CkZuqjAj

No errors, no despawn plugins

**Comment by sebastianbinder** [comment]
Without any Multiverse-Like plugin, how do you set your Gamelobby and your Gameworld?
But nevertheless: Have a look at https://github.com/Yannici/bedwars-reloaded/blob/master/shop.yml#L410 and the following lines. You need that exact configuration for TNT-sheep to work.
```yml
            - item1:
                item: GOLD_INGOT
                amount: 10
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: MONSTER_EGG
                meta: 91
                amount: 1
```
