### ISSUE TITLE
Make Trap effects more configurable

### ISSUE THREAD

**Issue by Koby99** [Yannici/bedwars-reloaded#406]
Ich wollte die Effekte von der Trap ändern aber egal wie ich es versucht habe wurde es immer auf die selben Effekte zurück gesetzt. Wie mach ich das das klappt

**Comment by sebastianbinder** [comment]
Hi @Koby99,
bitte beachte https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue - dann kann man versuchen dir zu helfen.

**Comment by Koby99** [comment]
Ich nutze die 1.2.8 also die neuste auf einem single Server error gibt es nicht in der Console und an anderen Plugins glaube ich liegt das Problem nicht.
Soll ich noch die shop.yml senden ?

**Comment by sebastianbinder** [comment]
Natürlich sollst du das.

**Comment by sebastianbinder** [comment]
@Koby99 bitte für jedermann sichtbar hier rein :)

**Comment by Koby99** [comment]
https://www.dropbox.com/sh/3jvj56wqyfwfas5/AAAAhVXMrl7Dqso6UpHCmyxza?dl=0   :P

**Comment by sebastianbinder** [comment]
Okay. Ich denke, es geht um den Teil mit Speed oder? (Unabhängig davon den Sinn des gleichzeitigen Verwendens von Speed und Slowness in Frage zu stellen…)
Ohne den exakten Code des Plugins an der Stelle zu kennen, denke ich, dass du nur die bestehenden Effekte modifizieren, aber nicht einfach einen neuen Effekt hinzufügen kannst.

**Comment by Koby99** [comment]
Ja ich wollte speed 100 machen XD

**Comment by Yannici** [comment]
Nein das geht nicht ... Welche Effekte zum Einsatz kommen ist fest gecodet. Da kann man per Config keine weiteren Effekte hinzufügen.

**Comment by sebastianbinder** [comment]
Ich öffne das mal wieder, weil an sich ist das ein schönes Feature, was man mal umsetzen kann :)

**Comment by Koby99** [comment]
Habt ihr/du schon was gemacht oder noch keine keine Idee wie man das umsetzt

**Comment by sebastianbinder** [comment]
@Koby99
Wenn es dazu schon was gäbe, dann hättest du es garantiert an dieser Stelle erfahren :)
1.9 ist im Moment um einiges wichtiger.

**Comment by Block-Build** [comment]
Should the style be the same?
```JavaScript
specials:
  trap:
    duration: 5
    blindness:
      enabled: false
      amplifier: 2
    2:
      enabled: true
      amplifier: 2
    show-particles: true
    play-sound: true
```
or something like:
```JavaScript
specials:
  trap:
    duration: 5
    effect:
    - blindness:
      ampilifer: 2
    - 2:
      ampilifer: 2
    show-particles: true
    play-sound: true
```

#needsdisscussion

**Comment by sebastianbinder** [comment]
I think it would be beste if we use [PotionEffect](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffect.html) and its (deserialize-constructor)[https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffect.html#PotionEffect(java.util.Map)] there. So the layout would look like the output of [serialize()](https://hub.spigotmc.org/javadocs/spigot/org/bukkit/potion/PotionEffect.html#serialize()) on a PotionEffect. This can be added to a list "effect" or "effects" (as in you second example).
This way would be the cleanest way and would look the same like in shop.yml (for not confusing users).

**Comment by Block-Build** [comment]
Could you senden an example it will look like with serialize?

**Comment by Block-Build** [comment]
I cant imagin serialize because duration and particle works global for all effects and should not changeable on every effect

**Comment by sebastianbinder** [comment]
I think, this could look like this:
```yml
specials:
  trap:
    play-sound: true
    effects:
    - ==: PotionEffect
      effect: 1
      duration: 1
      amplifier: 1
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 2
      duration: 1
      amplifier: 1
      ambient: true
      has-particles: true
    - ==: PotionEffect
      effect: 3
      duration: 1
      amplifier: 1
      ambient: true
      has-particles: true
```
I can imagine this pretty good, because I really can think of server owners who want to give them for example blindness or nausea for a longer time than weakness…
And always remember: Not using "custom-implementations" makes the plugin much more future proof for changes in spigot-api...
