### ISSUE TITLE
Welt Zerstörung

### ISSUE THREAD

**Issue by ZockerWelt** [Yannici/bedwars-reloaded#426]
Wenn man einen normalen Tnt-Block zündet zerstört er die Map obwohl ich world-destroy auf false gesetzt habe und das tnt schaf funktroniert nicht es blopt nur eine tnt auf das dann explodiert

**Comment by sebastianbinder** [comment]
Hi @ZockerWelt 
Bitte achte auf https://github.com/Yannici/bedwars-reloaded/wiki/HowTo:-Write-an-Issue - dann können wir dir vielleicht weiterhelfen.

**Comment by ZockerWelt** [comment]
ich nutzt die plugin version 1.2.7 und mein server läuft auf der version 1.8.8
installirte plugins: ControlTPAv2-0, EntityLWC, GameModer, LiftSign, Multiverse-Core-2.4, PermissionsEx-1.23.4, PlayerHeads, SimpleHomes, TablistPrefix v1.4.1, Vault, WarpPortals-5.6.5, worldedit-bukkit-6.1, worldguard-6.1
und in der config.yml von dem plugin steht  destroy-worldblocks auf false kannst du mir bitte helfen ich weis einfach nicht woran es liegt das die Mapblöcke trozdem zerstört werden

**Comment by Yannici** [comment]
WorldEdit und/oder WorldGuard sind desöfteren der Grund dafür!

**Comment by ZockerWelt** [comment]
aber was ist mit dem tnt-schaf da blopt beim setzen nur ein tnt auf was da los????

**Comment by Yannici** [comment]
Da hast du wohl das Spawnen von Schafen o.ä in WorldGuar/WorldEdit deaktiviert.

**Comment by sebastianbinder** [comment]
@ZockerWelt - bitte achte auch darauf, dass dein Shop richtig konfiguriert ist:
```yml
            - item1:
                item: GOLD_INGOT
                amount: 10
              reward:
                name: '&cTNT-Schaf'
                lore:
                    - "Aktiviere das TNT-Schaf! Es wird"
                    - "auf den nächsten Gegner zugehen"
                    - "und nach 8 Sekunden explodieren!"
                item: MONSTER_EGG
                meta: 91
                amount: 1
```
