### ISSUE TITLE
1.9 Update Bug-Tracker

### ISSUE THREAD

**Issue by sebastianbinder** [Yannici/bedwars-reloaded#447]
## In Progress
- [ ] Fix old shop
- Type: ``Bug``
- Description: Old shop is not completely working
- Responsible: @Yannici

### Important
``none``

### Not Important (doesn't need to be included in the next version)

- [ ] PlayerInteractEvent
- Type: ``Improvement``
- Description: Since 1.8 this event is getting called twice - left or right hand needs to be specified
- Further Information: https://hub.spigotmc.org/jira/browse/SPIGOT-1570
- Responsible: ``open``

## Done
- [x] Potions
- Type: ``Bug``
- Description: Generating potion with simple meta tags isn't working anymore. Update Potions to use PotionMeta
- Responsible: @sebastianbinder

- [x] Plugin-Updater
- Type: ``Feature``
- Description:  Plugin Updater needs to support the Minecraft 1.7 version drop
- Responsible: @ sebastianbinder

- [x] TNT-Sheep
- Type: ``Bug``
- Description:  Sheep do not really follow players, just pretty slow and not direct way to player
- Responsible: @Yannici

- [x] LeftHandEvent
- Type: ``Improvement``
- Description: Lobby Inventory could get in left hand - needs to be blocked
- Further Information: https://hub.spigotmc.org/jira/browse/SPIGOT-1532
- Responsible: @sebastianbinder

## No BedwarsRel Bugs
- [x] Tablist without team colors (Spigot Bug - fixed: https://hub.spigotmc.org/jira/browse/SPIGOT-1624)
- [x] Scoreboard not updating on bed destroy (wrong sound in config for bed destroy was the problem)
- [x] Gamemode 3 cannot fly through blocks (Bungeecord Bug - fix: https://hub.spigotmc.org/jira/browse/SPIGOT-1629)
- [x] http://pastebin.com/htH5BnAD -> fixed in https://hub.spigotmc.org/jira/browse/SPIGOT-1598

**Comment by sebastianbinder** [comment]
Als Gedächtnisstütze eine kleine Sammlung für mich...
- [] Spieler haben in Tab-Liste keine Farbe
- [] Scoreboard wird beim Bett-Abbauen nicht geupdatet (evtl. wg. falschem Sound in Config bisher)
- [] Gamemode 3: Fliegen durch Wände nicht möglich (evtl. wg. fehlerhaftem AAC)

**Comment by Granik24** [comment]
You maybe should write this in English I think..

**Comment by sebastianbinder** [comment]
Sorry for that - gonna translate it soon, but right now while testing it is a lot easier for me in German...

**Comment by sebastianbinder** [comment]
@Yannici - can you have a look on the Sheep thing?

**Comment by Yannici** [comment]
Yes, I will check that.

**Comment by sebastianbinder** [comment]
Potion with simple meta-data isn't supported in 1.9 anymore.
Need to change the way of buying potions.

What do you think - is this way of configuring a potion item in shop okay? A simple heal-potion could look like this:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Heal Potion'
                item: 373
                amount: 1
                effects:
                  - type: HEAL
```
But you can also add duration and amplifier:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Potion of Regeneration II'
                item: 373
                amount: 1
                effects:
                  - type: REGENERATION
                    duration: 20
                    amplifier: 2
```
Or combine multiple effects:
```yml
           - item1:
                item: IRON_INGOT
                amount: 3
              reward:
                name: 'Special Potion'
                item: 373
                amount: 1
                effects:
                  - type: HEAL
                  - type: Absorption
                    duration: 40
                    amplifier: 2
                  - type: REGENERATION
                    duration: 10
                    amplifier: 2
```

Pro: potions work again and you can make more special potions
Con: everybody upgrading to BedwarsRel 1.3.0 needs to update his shop

What do you guys think?

**Comment by Block-Build** [comment]
Is this 1.8 compatible too?

**Comment by Yannici** [comment]
The solution is good. Maybe we can implement a upgrade function which will upgrade the shop.yml automatically to the new potion solution.

**Comment by sebastianbinder** [comment]
>> Is this 1.8 compatible too?

@Block-Build - Yes, I tested both 1.8 and 1.9

>> The solution is good. Maybe we can implement a upgrade function which will upgrade the shop.yml automatically to the new potion solution.

@Yannici - Okay, I'm gonna push my code then. An updater would be nice, but you know … my java skills … we should integrate it with the config updater … feel free to have a look on it if you have any spare time for that :)

**Comment by HobbyzockerLP** [comment]
Nice! :)

**Comment by HobbyzockerLP** [comment]
Where i can download the new Version?

**Comment by sebastianbinder** [comment]
@HobbyzockerLP Just download the sources and build it with Ant.

**Comment by HobbyzockerLP** [comment]
Also muss ich selber den code ändern?

**Comment by Yannici** [comment]
Ja, aktuell gibt es noch keinen Build für die 1.9-Version.

**Comment by HobbyzockerLP** [comment]
Then I need help^^

**Comment by Block-Build** [comment]
@HobbyzockerLP I think you can find it on @sebastianbinder Jenkin site

**Comment by sebastianbinder** [comment]
No. There simply is no build yet, since we are not done with fixing all the errors. Everyone who would like to test the beta needs to know how to build it with Ant.

**Comment by HobbyzockerLP** [comment]
Do it for me, please :D

**Comment by Yannici** [comment]
@HobbyzockerLP Please be patient!

**Comment by komiss77** [comment]
Hi, Yannici! 
I've set up [your plugin](http://ostrov77.ru/uploads/bedwars.zip) to work with 1.9. All works, except TNTsheep. 
Look, maybe something useful to you and can make your job easier.
 Excuse me beforehand that made your code ugly)

**Comment by sebastianbinder** [comment]
@komiss77 So if you didn't fix the sheep, what exactly did you do then?

**Comment by komiss77** [comment]
Just people ask the beta version for 1.9.
  This can be used, in addition, there are some improvements (Spectator mode, rescue platform, etc.)

**Comment by sebastianbinder** [comment]
@komiss77 So please fork the project from here, then upload the code to your github branch and open a pull request. This makes it a lot easier for us to review your changes and implement them into the project.

**Comment by Yannici** [comment]
@komiss77 Stop uploading my plugin on your own page. This is not allowed. Please create an pull request.

**Comment by komiss77** [comment]
@Yannici I do not upload nothing on my own page. Code changed on local PC in NetBeans only for test and try to help you.

**Comment by Yannici** [comment]
@komiss77 No problem, just saying. Try to fork and make a pull request please.

**Comment by sebastianbinder** [comment]
Added tipped arrow support, use effects in the same way as potions:
```yml
            - item1:
                item: IRON_INGOT
                amount: 2
              reward:
                item: 440
                amount: 10
                effects:
                  - type: REGENERATION
                    duration: 45
                  - type: INCREASE_DAMAGE
                    duration: 180
                    amplifier: 5
```
