### ISSUE TITLE
Potions in shop not working

### ISSUE THREAD

**Issue by Yannici** [Yannici/bedwars-reloaded#508]
From review on spigotmc.org:

I using LAST spigot build for 1.9.2, but all potion in shop are uncraftable. Any help? 

We should check if that problem still exists. I will ask him for the shop.yml

**Comment by sebastianbinder** [comment]
@Yannici okay. I'm gonna check on the potions later this day. I really like how things first work on spigot and then don't work anymore all the time - NOT :-1:

**Comment by sebastianbinder** [comment]
Seems like they changed the PotionMeta again (and I didn't see that commit :/ ) :+1: https://hub.spigotmc.org/stash/projects/SPIGOT/repos/craftbukkit/commits/d39a750709e95fd38d39422b5274598731847024

**Comment by Yannici** [comment]
But the change doesn't looks like it should change the behavior like we use it... hm... we should check that though.

**Comment by sebastianbinder** [comment]
They introduced a "uncraftable" potion as a base potion. They reviews are talking about a uncraftable potion as well.… But I'll check on it. I think I've been running a Spigot build from 05/04/2016 until yesterday. So all my test results are based on that build… Now I'm working with a build from yesterday.

**Comment by sebastianbinder** [comment]
Test results:
New shop: Potions with meta-id don't work, potions with my "unofficial" effect method work
Old shop: Potions with meta-id work, potions with my "unofficial" effect method work (pretty funny - the last one didn't work in older builds…)

Trying to fix it now….

**Comment by sebastianbinder** [comment]
@Yannici 
I completely changed the look of shop.yml - now shop.yml uses ConfigurationSerializsation like we already do for RessourceSpawner and Teams. I also implemented an updater for updating old shops to the new scheme. I think using this way of adding items to shop is much better than the old one, because our code then is independent from API-changes. Every user can change his shop.yml according to used Spigot versions and our code is much more lightweight.
```yml
shop:
  swords:
    item: DIAMOND_SWORD
    name: Schwerter
    order: 10
    permission: bw.base
    lore:
    - Greife deine Gegner an!
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 8
      reward:
      - type: STICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            KNOCKBACK: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: WOOD_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: STONE_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 1
    - price:
      - type: GOLD_INGOT
        amount: 5
      reward:
      - type: IRON_SWORD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DAMAGE_ALL: 2
            KNOCKBACK: 1
    - price:
      - type: GOLD_INGOT
      reward:
      - type: SHIELD
    - empty
    - empty
    - empty
    - empty
    - empty
  pickaxes:
    item: DIAMOND_PICKAXE
    name: Spitzhacken
    order: 20
    permission: bw.base
    lore:
    - Zerstöre Blöcke!
    offers:
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: WOOD_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: STONE_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 2
    - price:
      - type: GOLD_INGOT
      reward:
      - type: IRON_PICKAXE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            DIG_SPEED: 3
    - empty
    - empty
    - empty
    - empty
    - empty
    - empty
    - empty
  bows:
    item: 261
    name: Bögen
    order: 30
    permission: bw.base
    lore:
    - Schieße deine Gegner mit einem Bogen herunter!
    offers:
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: BOW
    - price:
      - type: GOLD_INGOT
        amount: 7
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 1
    - price:
      - type: GOLD_INGOT
        amount: 13
      reward:
      - type: BOW
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            ARROW_DAMAGE: 2
            ARROW_KNOCKBACK: 1
    - price:
      - type: IRON_INGOT
        amount: 2
      reward:
      - type: ARROW
        amount: 10
    - empty
    - empty
    - empty
    - empty
    - empty
    - empty
  armor:
    item: DIAMOND_CHESTPLATE
    name: Rüstung
    order: 40
    permission: bw.base
    lore:
    - Schütze dich mit einer Rüstung!
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_HELMET
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_LEGGINGS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LEATHER_BOOTS
        meta:
          ==: ItemMeta
          meta-type: LEATHER_ARMOR
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 1
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 2
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: CHAINMAIL_CHESTPLATE
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          enchants:
            PROTECTION_ENVIRONMENTAL: 3
    - empty
    - empty
    - empty
    - empty
  blocks:
    item: SANDSTONE
    name: Blöcke
    order: 50
    permission: bw.base
    lore:
    - Baue dich mit Blöcken auf andere Inseln!
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 2
    - price:
      - type: CLAY_BRICK
        amount: 7
      reward:
      - type: ENDER_STONE
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: IRON_BLOCK
    - price:
      - type: CLAY_BRICK
        amount: 16
      reward:
      - type: GLOWSTONE
        amount: 4
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GLASS
    - price:
      - type: CLAY_BRICK
        amount: 64
      reward:
      - type: BRICK
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §4Schutzmauer
          lore:
          - Aktiviere es und erhalte sofort eine
          - 5x3 große Mauer vor dir!
    - empty
    - empty
    - empty
    - price:
      - type: CLAY_BRICK
        amount: 16
      reward:
      - type: SANDSTONE
        damage: 2
        amount: 32
  eat:
    item: GRILLED_PORK
    name: Essen
    order: 60
    permission: bw.base
    lore:
    - Kämpfe gegen den Hunger!
    offers:
    - price:
      - type: CLAY_BRICK
      reward:
      - type: APPLE
    - price:
      - type: CLAY_BRICK
        amount: 4
      reward:
      - type: GRILLED_PORK
        amount: 2
    - price:
      - type: GOLD_INGOT
        amount: 2
      reward:
      - type: GOLDEN_APPLE
    - empty
    - empty
    - empty
    - empty
    - empty
    - empty
    - empty
  usefulstuff:
    item: TNT
    name: Nützliche Sachen
    order: 70
    permission: bw.base
    lore:
    - Diese Sachen könnten dir echt helfen...
    offers:
    - price:
      - type: GOLD_INGOT
        amount: 2
      reward:
      - type: TNT
    - price:
      - type: IRON_INGOT
      reward:
      - type: CHEST
    - price:
      - type: GOLD_INGOT
        amount: 3
      reward:
      - type: BLAZE_ROD
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §cRettungsplattform
          lore:
          - Rette dich vor dem Abstürzen
          - mit der Rettungsplattform
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: STRING
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §7Trap
          lore:
          - Tritt ein Gegner drauf, wirst du informiert
          - und er kann sich nur eingeschränkt bewegen.
    - price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: SULPHUR
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §fTeleportationspuder
          lore:
          - Aktiviere dieses Pulver und du wirst
          - in 6 Sekunden an den Spawn teleportiert.
          - 'Achtung: Bewegen bricht den Vorgang ab!'
    - price:
      - type: CLAY_BRICK
      reward:
      - type: LADDER
    - price:
      - type: GOLD_INGOT
        amount: 13
      reward:
      - type: ENDER_PEARL
    - price:
      - type: CLAY_BRICK
        amount: 64
      reward:
      - type: MONSTER_EGG
        meta:
          ==: ItemMeta
          meta-type: UNSPECIFIC
          display-name: §cTNT-Schaf
          lore:
          - Aktiviere das TNT-Schaf! Es wird
          - auf den nächsten Gegner zugehen
          - und nach 8 Sekunden explodieren!
          internal: H4sIAAAAAAAAAONiYOBi4HTNK8ksqQxJTOdgYMpMYWANzkhNLWBgAAABt1TGHQAAAA==
    - empty
    - price:
      - type: IRON_INGOT
      reward:
      - type: REDSTONE_TORCH_ON
    - price:
      - type: GOLD_INGOT
      reward:
      - type: ENDER_CHEST
    - price:
      - type: CLAY_BRICK
        amount: 2
      reward:
      - type: TORCH
    - price:
      - type: CLAY_BRICK
        amount: 10
      reward:
      - type: WEB
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: FISHING_ROD
  drinks:
    item: POTION
    name: Tränke
    order: 80
    permission: bw.base
    lore:
    - Tränke flößen dir besondere Kraft ein!
    offers:
    - price:
      - type: IRON_INGOT
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: Trank der Direktheilung I
          custom-effects:
          - ==: PotionEffect
            effect: 6
            duration: 1
            amplifier: 0
            ambient: true
            has-particles: true
    - price:
      - type: IRON_INGOT
        amount: 5
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: Trank der Direktheilung II
          custom-effects:
          - ==: PotionEffect
            effect: 6
            duration: 1
            amplifier: 1
            ambient: true
            has-particles: true
    - price:
      - type: IRON_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: Trank der Geschwindigkeit I
          custom-effects:
          - ==: PotionEffect
            effect: 1
            duration: 3600
            amplifier: 0
            ambient: true
            has-particles: true
    - price:
      - type: GOLD_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: Trank der Stärke I
          custom-effects:
          - ==: PotionEffect
            effect: 5
            duration: 3600
            amplifier: 0
            ambient: true
            has-particles: true
    - price:
      - type: GOLD_INGOT
        amount: 7
      reward:
      - type: POTION
        meta:
          ==: ItemMeta
          meta-type: POTION
          display-name: Trank der Regeneration I
          custom-effects:
          - ==: PotionEffect
            effect: 10
            duration: 900
            amplifier: 0
            ambient: true
            has-particles: true
    - empty
    - empty
    - empty
    - empty
    - empty
schema-version: 1
```
That's how config looks like at the moment. Still work in progress, gonna do some more testing of the updater before pushing code...

**Comment by Block-Build** [comment]
@sebastianbinder Nice work!
Don't Forget the multiple Prices too.

**Comment by Yannici** [comment]
@sebastianbinder This is a good improvement, but will be too difficult for newbie users to change the shop easily. I see hundreds of Issues and Mails in Spigot having issues changing the shop ... :(

**Comment by Block-Build** [comment]
@Yannici sure... some people will use the easyest way, write a Ticket. But if they look at this example file they can change it self.

**Comment by Yannici** [comment]
@Block-Build Nope, they won't. They will just give up when see something like `==: ItemMeta`

**Comment by sebastianbinder** [comment]
The "price" part on the same level like the reward. price is a list (which contains the old "item1" and "item2")

Yes, it is more difficult. I know :/ So you are not happy about implementing this? This would solve so many issues and is so much more future-proof ....… And: those ItemMeta parts are optional. You only need them for renaming standard items or potions which simply needs some more knowledge about spigot :/

**Comment by sebastianbinder** [comment]
- price:
      - type: IRON_INGOT
        amount: 3
      reward:
      - type: IRON_BLOCK

Simple blocks are still pretty easy

**Comment by Yannici** [comment]
I'm happy about the implementation of the price and reward list. But I don't like the way how metadata will be configured, this will spam my postbox on spigot like its doing now with not-working potions :/

**Comment by sebastianbinder** [comment]
Mm. The meta part is the only reason I'm doing this, since ItemMeta in Spigot is just a mess :/ Gonna think about how to make it look better. But in my opinion this is the only proper way of making the shop update proof and solving all this potion issues :/

**Comment by Yannici** [comment]
You're right but we need to make that easier, sorry. I think the best way is to make everything optional were is possible to make it optional. Even if we have to write own parsers ... Easy configuration has to be the goal. 

Example:
__from:__
```yaml
reward:
  - type: POTION
    meta:
      ==: ItemMeta
      meta-type: POTION
      display-name: Trank der Regeneration I
      custom-effects:
      - ==: PotionEffect
        effect: 10
        duration: 900
        amplifier: 0
        ambient: true
        has-particles: true
```

__to:__
```yaml
reward:
  - type: POTION
    meta:
      display-name: Trank der Regeneration I
      effect: 10
      duration: 900
```

Should easily be possible by writing parsers for every special item-type, if needed!
